/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import data.User;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author imkus
 */
public class DetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailsPanel
     */
    JPanel mainPanel;
    CardLayout cardLayout;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("LLLL d, yyyy");

    public DetailsPanel(JPanel mainPanel, User user) {
        initComponents();
        this.mainPanel = mainPanel;
        cardLayout = (CardLayout) mainPanel.getLayout();
        firstNameLabel.setText(user.getFirstName());
        lastNameLabel.setText(user.getLastName());
        birthDateLabel.setText(user.getBirthDate().format(formatter));
        genderLabel.setText(user.getGender().toString());
        startDateLabel.setText(user.getStartDate().format(formatter));
        levelLabel.setText(user.getLevel());
        phoneLabel.setText(user.getPhone());
        emailLabel.setText(user.getEmail());
        employeeIdLabel.setText(user.getEmployeeId());
        imageView.setIcon(new ImageIcon(user.getProfileImage()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        imageView = new javax.swing.JLabel();
        firstNameTitleLabel = new javax.swing.JLabel();
        lastNameTitleLabel = new javax.swing.JLabel();
        birthTitleLabel = new javax.swing.JLabel();
        genderTitleLabel = new javax.swing.JLabel();
        startTitleLabel = new javax.swing.JLabel();
        levelTitleLabel = new javax.swing.JLabel();
        phoneTitleLabel = new javax.swing.JLabel();
        emailTitleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        employeeIdTitleLabel = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();

        backButton.setText("Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePanel.add(imageView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        firstNameTitleLabel.setText("First Name:");

        lastNameTitleLabel.setText("Last Name:");

        birthTitleLabel.setText("DOB:");

        genderTitleLabel.setText("Gender:");

        startTitleLabel.setText("Start Date:");

        levelTitleLabel.setText("Level");

        phoneTitleLabel.setText("Phone:");

        emailTitleLabel.setText("Email:");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleLabel.setText("Employee Details");

        employeeIdTitleLabel.setText("Employee ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(titleLabel)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeeIdTitleLabel)
                    .addComponent(levelTitleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneTitleLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(birthTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(genderTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(startTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lastNameTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstNameTitleLabel))))
                    .addComponent(emailTitleLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(birthDateLabel)
                    .addComponent(genderLabel)
                    .addComponent(startDateLabel)
                    .addComponent(levelLabel)
                    .addComponent(phoneLabel)
                    .addComponent(emailLabel)
                    .addComponent(employeeIdLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTitleLabel)
                            .addComponent(firstNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTitleLabel)
                            .addComponent(lastNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthTitleLabel)
                            .addComponent(birthDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderTitleLabel)
                            .addComponent(genderLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startTitleLabel)
                            .addComponent(startDateLabel)))
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelTitleLabel)
                    .addComponent(levelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTitleLabel)
                    .addComponent(phoneLabel)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTitleLabel)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeIdTitleLabel)
                    .addComponent(employeeIdLabel))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.first(mainPanel);

    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JLabel birthTitleLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTitleLabel;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JLabel employeeIdTitleLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameTitleLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderTitleLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel imageView;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameTitleLabel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelTitleLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneTitleLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel startTitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
